/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface definitions {
  CaseChapterExam: {
    /**
     * 案例Id
     */
    caseId?: string;
    /**
     * 章节Id
     */
    chapterId?: string;
    /**
     * 测验库中的测验Id
     */
    examId?: string;
    /**
     * 测验标题
     */
    examTitle?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 创建人
     */
    userId?: string;
  };
  NlpLexerResponse: {
    /**
     * 分析词组
     */
    items?: definitions["NlpLexerResponseItem"][];
  };
  "BaseResponseBody«List«CaseAppendix»»": {
    /**
     * 响应实体
     */
    data?: definitions["CaseAppendix"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  BPhotoInfo: {
    /**
     * 账号
     */
    code?: string;
    /**
     * 图片相对地址
     */
    url?: string;
  };
  "公共REST返回Body对象«PageResponse«TeacherInfoMemberResp»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«TeacherInfoMemberResp»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  ApkDownloadTask: {
    /**
     * 是否有版本更新
     */
    hasUpdate?: boolean;
    /**
     * apk文件下载地址
     */
    href?: string;
  };
  "公共REST返回Body对象«Page«Examine»»": {
    /**
     * 响应实体
     */
    data?: definitions["Page«Examine»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«NlpLexerResponse»": {
    /**
     * 响应实体
     */
    data?: definitions["NlpLexerResponse"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«List«TeacherCaseCategory»»": {
    /**
     * 响应实体
     */
    data?: definitions["TeacherCaseCategory"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  ChangeUserInfoRequest: {
    /**
     * 年龄
     */
    age?: string;
    /**
     * 班级Id数组
     */
    classIds?: string;
    /**
     * 账号
     */
    code?: string;
    /**
     * 是否禁用(true or false)
     */
    disable?: string;
    /**
     * 新邮箱
     */
    email?: string;
    /**
     * 新姓名
     */
    name?: string;
    /**
     * 昵称
     */
    nickname?: string;
    /**
     * 生日
     */
    personalSignature?: string;
    /**
     * 个人简介
     */
    resume?: string;
    /**
     * 新自我介绍
     */
    selfIntroduction?: string;
    /**
     * 性别(0:女;1:男)
     */
    sex?: string;
    /**
     * 职业
     */
    title?: string;
  };
  NotePageRequest: {
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
  };
  ListClassMemberRequest: {
    /**
     * 班级名模糊查询
     */
    classNameLike?: string;
    /**
     * 班级Id
     */
    classRoom_uuid?: string;
    /**
     * 模糊查询（账号或姓名）
     */
    keyWord?: string;
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
    /**
     * 教师Id
     */
    teacherId?: string;
    /**
     * 用户Id
     */
    userId?: string;
  };
  "PageResponse«CountStudyNoteWithCase»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["CountStudyNoteWithCase"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  "公共REST返回Body对象«CaseNote»": {
    /**
     * 响应实体
     */
    data?: definitions["CaseNote"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«List«TeacherCaseMixResponse»»": {
    /**
     * 响应实体
     */
    data?: definitions["TeacherCaseMixResponse"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  PageQueryRequest: {
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
  };
  SoftConfigResult: {
    /**
     * copyRight Value
     */
    copyRightValue?: string;
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 软件名称
     */
    softName?: string;
    /**
     * 请求是否成功
     */
    success?: boolean;
    /**
     * 是否使用CAS登录(0 or 1)
     */
    useCas?: string;
  };
  QueryUserParam: {
    /**
     * 查询.是否禁用
     */
    disable?: string;
    /**
     * 查询.邮箱(模糊查询)
     */
    email?: string;
    /**
     * 查询.用户名称(模糊查询)
     */
    name?: string;
    /**
     * 查询.角色  0:学生;1:教师;2:管理员
     */
    role?: number;
    /**
     * 查询.用户代码(模糊查询)
     */
    userCode?: string;
  };
  "Page«Examine»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["Examine"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  ScoreDetail: {
    /**
     * 班级名称
     */
    className?: string;
    /**
     * 得分详细列表
     */
    scoreArray?: { [key: string]: any }[];
    /**
     * 学生头像
     */
    stuCover?: string;
    /**
     * 学生名
     */
    stuName?: string;
    /**
     * 老师Id
     */
    teacherId?: string;
    /**
     * 老师姓名
     */
    teacherName?: string;
  };
  "BaseResponseBody«List«StudyTrendResponse»»": {
    /**
     * 响应实体
     */
    data?: definitions["StudyTrendResponse"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "公共REST返回Body对象«PageResponse«TeacherMemberResp»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«TeacherMemberResp»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«PageResponse«CaseTag»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«CaseTag»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "PageResponse«StudyRecordPage»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["StudyRecordPage"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  OtherStuProgressRequest: {
    /**
     * 案例Id
     */
    caseId: string;
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
  };
  ListClassRequest: {
    /**
     * 班级Id
     */
    id?: string;
    /**
     * 班级Ids
     */
    ids?: string[];
    /**
     * 模糊查询条件关键字
     */
    keyWord?: string;
    /**
     * 班级名称
     */
    name?: string;
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
    /**
     * 是否升序/降序
     */
    seqAsc?: boolean;
    /**
     * 排序字段名
     */
    seqColumn?: string;
    /**
     * 教师Id
     */
    userId?: string;
  };
  "BaseResponseBody«List«StudyTopResponse»»": {
    /**
     * 响应实体
     */
    data?: definitions["StudyTopResponse"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  QRLoginRequest: {
    /**
     * 二维码令牌
     */
    qrToken: string;
  };
  "BaseResponseBody«ApkDownloadTask»": {
    /**
     * 响应实体
     */
    data?: definitions["ApkDownloadTask"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«PageResponse«StudyRecordPage»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«StudyRecordPage»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  QueryClassRequest: {
    /**
     * 班级Id
     */
    id?: string;
    /**
     * 班级Ids
     */
    ids?: string[];
    /**
     * 模糊查询条件关键字
     */
    keyWord?: string;
    /**
     * 班级名称
     */
    name?: string;
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
    /**
     * 是否升序/降序
     */
    seqAsc?: boolean;
    /**
     * 排序字段名
     */
    seqColumn?: string;
  };
  "BaseResponseBody«PageResponse«TeacherCaseStuProgress»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«TeacherCaseStuProgress»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  CaseTag: {
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 标签编号(int)
     */
    serialNumber?: number;
    /**
     * 标签名称
     */
    tagName?: string;
    /**
     * 更新时间
     */
    updateDate?: string;
  };
  CheckTokenRequest: { token: string };
  "PageResponse«TeacherMemberResp»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["TeacherMemberResp"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  StuScore: {
    /**
     * 总案例数
     */
    caseCount?: number;
    /**
     * classId@Transient
     */
    classId?: string;
    /**
     * 完成案例数
     */
    compCaseCount?: number;
    /**
     * 算分时间
     */
    createDate?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 笔记数
     */
    noteCount?: number;
    /**
     * 课时数
     */
    periodCount?: number;
    /**
     * 分数
     */
    score?: number;
    /**
     * 一级分类Id
     */
    seniorCategoryId?: string;
    /**
     * 教师Id
     */
    teacherId?: string;
    /**
     * 学生Id
     */
    userId?: string;
    /**
     * 用户名@Transient
     */
    userName?: string;
  };
  "公共REST返回Body对象«List«CaseNote»»": {
    /**
     * 响应实体
     */
    data?: definitions["CaseNote"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  ListTeacherMemberRequest: {
    /**
     * 班级Id
     */
    classId?: string;
    /**
     * 班级名模糊查询
     */
    classNameLike?: string;
    /**
     * 用户名模糊查询（账号或姓名）
     */
    keyWord?: string;
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
    /**
     * 教师Id
     */
    teacherId?: string;
  };
  GetStudyNoteWithCase: {
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
    /**
     * 用户Id
     */
    userId?: string;
  };
  "BaseResponseBody«CasesPageByCategory»": {
    /**
     * 响应实体
     */
    data?: definitions["CasesPageByCategory"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "公共REST返回Body对象«PageResponse«ClassMemberInfo»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«ClassMemberInfo»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«PageResponse«CasesPageByCategory»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«CasesPageByCategory»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«boolean»": {
    /**
     * 响应实体
     */
    data?: boolean;
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  StudyRecord: {
    /**
     * 异常标记@Transient
     */
    abnormalMark?: boolean;
    /**
     * 案例Id
     */
    caseId?: string;
    /**
     * 完成时间
     */
    doneDate?: string;
    /**
     * 学习时长(秒数)
     */
    duration?: number;
    /**
     * 学习设备
     */
    equipment?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 一级分类Id
     */
    seniorCategoryId?: string;
    /**
     * 加入时间
     */
    startDate?: string;
    /**
     * 学习状态:0-待学习/1-学习中/2-已完成/-1-授权状态
     */
    studyStatus?: number;
    /**
     * 用户id
     */
    userId?: string;
  };
  ForgetPasswordByMailRequest: {
    /**
     * 邮箱
     */
    email?: string;
    /**
     * 用户账号
     */
    userCode?: string;
  };
  StudyTrendResponse: {
    /**
     * 显示文字
     */
    context?: string;
    /**
     * 增长率
     */
    rate?: number;
    /**
     * 分数
     */
    score?: number;
  };
  CaseNote: {
    /**
     * 案例Id
     */
    caseId?: string;
    /**
     * 笔记内容
     */
    content?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 案例标题@Transient
     */
    mainTitle?: string;
    /**
     * 课时Id
     */
    periodId?: string;
    /**
     * 课时名称@Transient
     */
    periodTitle?: string;
    /**
     * 一级分类Id
     */
    seniorCategoryId?: string;
    /**
     * 更新时间
     */
    updateDate?: string;
    /**
     * 作者(用户id)
     */
    userId?: string;
    /**
     * 作者名(用户名)@Transient
     */
    userName?: string;
  };
  "BaseResponseBody«Page«CaseTag»»": {
    /**
     * 响应实体
     */
    data?: definitions["Page«CaseTag»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«List«CaseTag»»": {
    /**
     * 响应实体
     */
    data?: definitions["CaseTag"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  NlpWordSimEmbeddingResponse: {
    /**
     * 相似度结果
     */
    score?: number;
  };
  "BaseResponseBody«List«CaseChapter»»": {
    /**
     * 响应实体
     */
    data?: definitions["CaseChapter"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  QueryUserRequest: {
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
    queryParam?: definitions["QueryUserParam"];
  };
  ListTeacherInfoMemberRequest: {
    /**
     * 班级Id
     */
    classId?: string;
    /**
     * 班级名模糊查询
     */
    classNameLike?: string;
    /**
     * 创建日期 格式：2020-11-04
     */
    createTime?: string;
    /**
     * 是否禁用
     */
    disable?: boolean;
    /**
     * 用户名模糊查询（（名字、手机、邮箱））
     */
    keyWord?: string;
    /**
     * 排序列名(userName,phone,sex,school,lastLoginTime)
     */
    orderColumnName?: string;
    /**
     * 是否降序
     */
    orderDesc?: boolean;
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
    /**
     * 教师Id
     */
    teacherId?: string;
  };
  "BaseResponseBody«CaseTag»": {
    /**
     * 响应实体
     */
    data?: definitions["CaseTag"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "公共REST返回Body对象«PageResponse«ClassMember»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«ClassMember»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  IdsRequest: {
    /**
     * 用户Id
     */
    ids?: string[];
  };
  "BaseResponseBody«CasesWithCategoryName»": {
    /**
     * 响应实体
     */
    data?: definitions["CasesWithCategoryName"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  CountRecordsByType: {
    /**
     * 异常记录数
     */
    countAbnormal?: number;
    /**
     * 全部记录数
     */
    countAll?: number;
    /**
     * 已完成记录数
     */
    countFinished?: number;
    /**
     * 待学习记录数
     */
    countNotStart?: number;
    /**
     * 学习中记录数
     */
    countStarted?: number;
  };
  ScoreTarget: {
    /**
     * 异常时长
     */
    exceptionTime?: number;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 笔记上限
     */
    noteUpperLimit?: number;
    /**
     * 笔记权重
     */
    noteWeight?: number;
    /**
     * 学习上限
     */
    studyUpperLimit?: number;
    /**
     * 学习权重
     */
    studyWeight?: number;
    /**
     * 创建人(用户Id)
     */
    userId?: string;
  };
  ListERUser: {
    /**
     * 授权管理Id
     */
    examineId: string;
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
  };
  QueryStudyScoreRequest: {
    /**
     * 分类Id
     */
    categoryId?: string;
    /**
     * 班级Id
     */
    classId?: string;
    /**
     * 止时间
     */
    endDate?: string;
    /**
     * 起时间
     */
    startDate?: string;
    /**
     * 教师Id
     */
    teacherId?: string;
    /**
     * 0-本日,1-本周,2-本月
     */
    type?: number;
    /**
     * 学生Id
     */
    userId?: string;
  };
  TeacherInfoMemberResp: {
    /**
     * 管理班级id数组
     */
    classIds?: string;
    /**
     * 管理班级名称数组
     */
    classNames?: string;
    /**
     * 教师头像
     */
    headPath?: string;
    /**
     * 最后登录时间
     */
    lastLoginTime?: string;
    /**
     * 手机号
     */
    phone?: string;
    /**
     * 学校
     */
    school?: string;
    /**
     * 1男 2女 3其他
     */
    sex?: number;
    /**
     * 是否禁用
     */
    userDisable?: boolean;
    /**
     * 教师账号
     */
    userId?: string;
    /**
     * 教师名称
     */
    userName?: string;
  };
  MyStudyCaseWithProgress: {
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
    /**
     * 学习状态:学习中/已完成
     */
    studyStatus?: string;
  };
  TeacherCaseChapter: {
    /**
     * 案例Id
     */
    caseId?: string;
    /**
     * 章节排序
     */
    chapterSeq?: number;
    /**
     * 标题(章节名称)
     */
    chapterTitle?: string;
    /**
     * 创建日期
     */
    createChapterDate?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 课时列表@Transient
     */
    periodList?: definitions["TeacherCaseChapterPeriod"][];
    /**
     * 创建人
     */
    userId?: string;
  };
  "BaseResponseBody«NlpSimnetResponse»": {
    /**
     * 响应实体
     */
    data?: definitions["NlpSimnetResponse"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  MergeClassRequest: {
    /**
     * 是否禁用
     */
    disable?: boolean;
    /**
     * 主键Id
     */
    id?: string;
    /**
     * 班级名称
     */
    name: string;
    /**
     * 备注
     */
    remarks?: string;
    /**
     * 管理老师账号，不传则不变
     */
    teacherCodes?: string;
  };
  NlpLexerResponseItem: { score?: number; word?: string };
  "BaseResponseBody«StudyRecord»": {
    /**
     * 响应实体
     */
    data?: definitions["StudyRecord"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«TeacherCaseChapterPeriod»": {
    /**
     * 响应实体
     */
    data?: definitions["TeacherCaseChapterPeriod"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  TeacherCasesIndexRequest: {
    /**
     * 分类Id(一级分类Id)
     */
    categoryId: string;
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
    /**
     * 案例类型:all-(默认)全部 / recommend-推荐
     */
    type: string;
  };
  "Page«CaseTag»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["CaseTag"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  Class: {
    /**
     * 禁用
     */
    disable?: boolean;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 班级名称
     */
    name?: string;
    /**
     * 备注
     */
    remarks?: string;
    /**
     * 学生人数 @Transient
     */
    stuNum?: number;
    /**
     * 老师ID @Transient
     */
    teacherCodes?: string;
    /**
     * 老师名称 @Transient
     */
    userNames?: string;
    /**
     * 是否是教师、管理员专用班级
     */
    vipClass?: boolean;
  };
  "BaseResponseBody«StudyRecordStatist»": {
    /**
     * 响应实体
     */
    data?: definitions["StudyRecordStatist"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  RecordDistributionResponse: {
    /**
     * 显示文字
     */
    type?: string;
    /**
     * 比率
     */
    value?: number;
  };
  MyStudyCasesRequest: {
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
    /**
     * 学习状态:0-待学习/1-学习中/2-已完成
     */
    studyStatus?: number;
    /**
     * 用户Id
     */
    userId?: string;
  };
  SearchRequest: {
    /**
     * 查询关键字
     */
    keyWords?: string;
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
  };
  "Page«MyStudyCasesResponse»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["MyStudyCasesResponse"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  "BaseResponseBody«PageResponse«CaseAppendix»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«CaseAppendix»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«LoginUserResponse»": {
    /**
     * 响应实体
     */
    data?: definitions["LoginUserResponse"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  StudyRecordFormData: {
    tableData?: { [key: string]: any }[];
    tableName?: { [key: string]: any }[];
  };
  UserInfo: {
    /**
     * 生日
     */
    birthday?: string;
    /**
     * 学历
     */
    education?: string;
    /**
     * 邮箱
     */
    email?: string;
    /**
     * 毕业时间
     */
    graduationTime?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 所学专业
     */
    major?: string;
    /**
     * 用户姓名@Transient
     */
    name?: string;
    /**
     * 手机号
     */
    phone?: string;
    /**
     * 籍贯
     */
    place?: string;
    /**
     * 职称
     */
    professional?: string;
    /**
     * 备注
     */
    remarks?: string;
    /**
     * 学校
     */
    school?: string;
    /**
     * 1男 2女 3其他
     */
    sex?: number;
    /**
     * 学号
     */
    stuCode?: string;
    /**
     * 座机
     */
    telephone?: string;
    /**
     * 用户Id
     */
    userId?: string;
    /**
     * 微信号
     */
    weChat?: string;
  };
  "BaseResponseBody«List«NoteInfoInMyStudy»»": {
    /**
     * 响应实体
     */
    data?: definitions["NoteInfoInMyStudy"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«int»": {
    /**
     * 响应实体
     */
    data?: number;
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  ChangePasswordRequest: {
    /**
     * 账号
     */
    code: string;
    /**
     * 新密码
     */
    newPassword?: string;
    /**
     * 原密码
     */
    oldPassword?: string;
  };
  CaseAppendix: {
    /**
     * 文件标识:资料文件/备用文件
     */
    appendixMark?: number;
    /**
     * 文件名
     */
    appendixName?: string;
    /**
     * 附件路径:
     */
    appendixPath?: string;
    /**
     * 文件大小(单位:友好显示)
     */
    appendixSize?: string;
    /**
     * 文件类型:视频/音频/图文
     */
    appendixType?: number;
    /**
     * 案例Id
     */
    caseId?: string;
    /**
     * 相关的课时(课时Id)
     */
    chapterId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 状态更新时间
     */
    updateDate?: string;
    /**
     * 创建人
     */
    userId?: string;
  };
  EditTeacherCaseRequest: {
    /**
     * 附件列表@Transient
     */
    appendixList: definitions["TeacherCaseAppendix"][];
    /**
     * 案例封面(图片路径)
     */
    caseCover: string;
    /**
     * 章节列表@Transient
     */
    chapterList: definitions["TeacherCaseChapter"][];
    /**
     * 当前案例总课时数@Transient
     */
    countCasePeriod: number;
    /**
     * 当前案例已学习课时数@Transient
     */
    countfinishedPeriod: number;
    /**
     * 案例目标
     */
    goal: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 案例简介
     */
    intro: string;
    /**
     * 所属二级分类(二级分类Id)
     */
    juniorCategory: string;
    /**
     * 二级分类名@Transient
     */
    juniorCategoryName: string;
    /**
     * 最近学习课时Id@Transient
     */
    lastStudyPeriodId: string;
    /**
     * 案例名称(案例标题)
     */
    mainTitle: string;
    /**
     * 是否是推荐案例:是/否
     */
    recommended: boolean;
    /**
     * 所属一级分类(一级分类Id)
     */
    seniorCategory: string;
    /**
     * 一级分类名@Transient
     */
    seniorCategoryName: string;
    /**
     * 原二级分类Id
     */
    sourceJuniorCategoryId: string;
    /**
     * 案例状态(int):0－已关闭/1-未发布/2－已发布
     */
    status: number;
    /**
     * 学习进度@Transient
     */
    studyProgress: number;
    /**
     * 学习状态@Transient
     */
    studyStatus: string;
    /**
     * 案例副标题
     */
    subTitle: string;
    /**
     * 适应人群
     */
    suitableCrowd: string;
    /**
     * 标签列表@Transient
     */
    tagList: definitions["CaseTag"][];
    /**
     * 标签名对象
     */
    tagNameList?: string[];
    /**
     * 案例教师名@Transient
     */
    teacherName: string;
    /**
     * 是否是典型案例:是/否
     */
    typical: boolean;
    /**
     * 更新时间
     */
    updateDate: string;
    /**
     * 创建人(用户id)
     */
    userId: string;
  };
  TeacherMemberResp: {
    /**
     * 管理班级id数组
     */
    classIds?: string;
    /**
     * 管理班级名称数组
     */
    classNames?: string;
    /**
     * 教师头像
     */
    headPath?: string;
    /**
     * 是否禁用
     */
    userDisable?: boolean;
    /**
     * 教师账号
     */
    userId?: string;
    /**
     * 教师名称
     */
    userName?: string;
  };
  NlpSimnetResponse: {
    /**
     * 相似度结果
     */
    score?: number;
  };
  TeacherCaseAppendix: {
    /**
     * 文件标识:资料文件/备用文件
     */
    appendixMark?: number;
    /**
     * 文件名
     */
    appendixName?: string;
    /**
     * 附件路径:
     */
    appendixPath?: string;
    /**
     * 文件大小(单位:友好显示)
     */
    appendixSize?: string;
    /**
     * 文件类型:视频/音频/图文
     */
    appendixType?: number;
    /**
     * 案例Id
     */
    caseId?: string;
    /**
     * 相关的课时(课时Id)
     */
    chapterId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 状态更新时间
     */
    updateDate?: string;
    /**
     * 创建人
     */
    userId?: string;
  };
  CreateOrUpdateClassMemberRequest: {
    /**
     * 班级Id
     */
    classId: string;
    /**
     * 是否教师
     */
    isTeacher?: string;
    /**
     * 用户名称
     */
    name?: string;
    /**
     * 学员Id
     */
    userId: string;
  };
  UserLoginHistory: {
    /**
     * 班级名称@Transient
     */
    className?: string;
    /**
     * 电子邮箱
     */
    email?: string;
    /**
     * 登录失败历史
     */
    failed?: boolean;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 登录地址
     */
    loginAddr?: string;
    loginIp?: string;
    /**
     * 登录时间
     */
    loginTime?: string;
    /**
     * 用户名
     */
    name?: string;
    /**
     * 用户code
     */
    userCode?: string;
  };
  LoginUserResponse: {
    /**
     * 用户号
     */
    code?: string;
    disable?: boolean;
    /**
     * 姓名
     */
    name?: string;
    /**
     * 角色(admin;teacher;student)
     */
    role?: string;
    token?: string;
  };
  StudyStatistResponse: {
    /**
     * 值
     */
    value?: string;
    /**
     * X
     */
    xValue?: string;
    /**
     * Y
     */
    yValue?: number;
  };
  CaseTagEditRequest: {
    /**
     * 标签Id
     */
    tagId?: string;
    /**
     * 标签名称
     */
    tagName?: string;
  };
  "公共REST返回Body对象«Class»": {
    /**
     * 响应实体
     */
    data?: definitions["Class"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  FiltrateRecordRequest: {
    /**
     * 结束时间(时间戳)
     */
    endTime: number;
    /**
     * 案例名称
     */
    mainTitle: string;
    /**
     * 班级名/用户名
     */
    mixedName: string;
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
    /**
     * 课程(一级分类Id)
     */
    seniorCategory: string;
    /**
     * 开始时间(时间戳)
     */
    startTime: number;
    /**
     * 学习记录的状态:全部/待学习/学习中/已完成/异常
     */
    statusStr: string;
  };
  "BaseResponseBody«Void»": {
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "PageResponse«Class»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["Class"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  "BaseResponseBody«TeacherCaseCategory»": {
    /**
     * 响应实体
     */
    data?: definitions["TeacherCaseCategory"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  UserQRLoginRecord: {
    /**
     * 角色.是否是管理员@Transient
     */
    admin?: boolean;
    /**
     * 创建时间
     */
    createTime?: string;
    /**
     * 失效时间
     */
    expireTime?: string;
    /**
     * 二维码图片地址
     */
    qrImagePath?: string;
    /**
     * 二维码图片Baser64码
     */
    qrImagePathBase64?: string;
    /**
     * 二维码令牌
     */
    qrToken?: string;
    /**
     * 状态,选项为:0:开始;1:手机已扫码;999:手机已登录;-999:二维码失效
     */
    state?: number;
    /**
     * 角色.是否是教师@Transient
     */
    teacher?: boolean;
    /**
     * 登录成功后用户token
     */
    token?: string;
    /**
     * 用户对象@Transient
     */
    userId?: string;
  };
  ChangeUserRoleRequest: {
    /**
     * 是否是管理员
     */
    admin?: boolean;
    /**
     * 账号
     */
    code?: string;
    /**
     * 是否是学生
     */
    student?: boolean;
    /**
     * 是否是教师
     */
    teacher?: boolean;
  };
  "PageResponse«CasesPageByCategory»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["CasesPageByCategory"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  ListExamineRequest: {
    /**
     * id
     */
    id?: string;
    /**
     * 排序字段名（a.disable,a.title,a.remarks,a.updateTime）
     */
    orderColumnName?: string;
    /**
     * 正序、倒序排列
     */
    orderDesc?: boolean;
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
    /**
     * 方案名称
     */
    title?: string;
  };
  "BaseResponseBody«StudyRecordInfo»": {
    /**
     * 响应实体
     */
    data?: definitions["StudyRecordInfo"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  QueryLoginHistoryRequest: {
    /**
     * 查询.用户邮箱
     */
    email?: string;
    /**
     * 查询.登录结束时间
     */
    endTime?: number;
    /**
     * 查询.用户姓名
     */
    name?: string;
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
    /**
     * 查询.登录开始时间
     */
    startTime?: number;
    /**
     * 查询.用户号
     */
    userCode?: string;
  };
  "公共REST返回Body对象«int»": {
    /**
     * 响应实体
     */
    data?: number;
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  Cases: {
    /**
     * 附件列表@Transient
     */
    appendixList?: definitions["CaseAppendix"][];
    /**
     * 案例封面(图片路径)
     */
    caseCover?: string;
    /**
     * 章节列表@Transient
     */
    chapterList?: definitions["CaseChapter"][];
    /**
     * 案例目标
     */
    goal?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 案例简介
     */
    intro?: string;
    /**
     * 所属二级分类(二级分类Id)
     */
    juniorCategory?: string;
    /**
     * 案例名称(案例标题)
     */
    mainTitle?: string;
    /**
     * 是否是推荐案例:true-是/false-否
     */
    recommended?: boolean;
    /**
     * 所属一级分类(一级分类Id)
     */
    seniorCategory?: string;
    /**
     * 案例状态(int):0－已关闭/1-未发布/2－已发布
     */
    status?: number;
    /**
     * 案例副标题
     */
    subTitle?: string;
    /**
     * 适应人群
     */
    suitableCrowd?: string;
    /**
     * 标签列表@Transient
     */
    tagList?: definitions["CaseTag"][];
    /**
     * 是否是典型案例:true-是/false-否
     */
    typical?: boolean;
    /**
     * 更新时间
     */
    updateDate?: string;
    /**
     * 创建人(用户id)
     */
    userId?: string;
  };
  "PageResponse«TeacherCases»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["TeacherCases"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  "PageResponse«ClassMember»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["ClassMember"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  "BaseResponseBody«Page«MyStudyCasesResponse»»": {
    /**
     * 响应实体
     */
    data?: definitions["Page«MyStudyCasesResponse»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  NoteInfoByCaseAndUser: {
    /**
     * 案例Id
     */
    caseId?: string;
    /**
     * 用户Id
     */
    userId?: string;
  };
  TeacherCaseCategory: {
    /**
     * 是否能删除 ture-能删,false-不能删
     */
    canDel?: boolean;
    /**
     * 案例数量@Transient
     */
    caseCount?: number;
    /**
     * 分类编码
     */
    categoryCode?: string;
    /**
     * 分类描述
     */
    categoryDescribe?: string;
    /**
     * 分类名称
     */
    categoryName?: string;
    /**
     * 是否显示 true-显示,false-不显示
     */
    display?: boolean;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 父级分类Id 如果为父级 NULL
     */
    parentId?: string;
    /**
     * 排序
     */
    seq?: number;
    /**
     * 修改时间
     */
    updateDate?: string;
    /**
     * 创建人
     */
    userId?: string;
  };
  "BaseResponseBody«PageResponse«CaseNote»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«CaseNote»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  MyStudyCasesResponse: {
    /**
     * 案例封面
     */
    caseCover?: string;
    /**
     * 案例Id
     */
    caseId?: string;
    /**
     * 学习时长:(秒数)
     */
    duration?: number;
    /**
     * 案例名
     */
    mainTitle?: string;
    /**
     * 学习进度:(百分数)
     */
    studyProcess?: number;
    /**
     * 学习状态:0-待学习/1-学习中/2-已完成
     */
    studyStatus?: number;
  };
  "公共REST返回Body对象«PageResponse«ExamineExistUser»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«ExamineExistUser»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "PageResponse«CaseTag»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["CaseTag"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  "BaseResponseBody«CaseAppendix»": {
    /**
     * 响应实体
     */
    data?: definitions["CaseAppendix"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "公共REST返回Body对象«CaseCategory»": {
    /**
     * 响应实体
     */
    data?: definitions["CaseCategory"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  Examine: {
    /**
     * 是否停用
     */
    disable?: boolean;
    /**
     * 停用原因
     */
    disableMsg?: string;
    /**
     * 启用原因
     */
    enableMsg?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 授权方案描述
     */
    remarks?: string;
    /**
     * 二级分类Id（传参用）@Transient
     */
    subCategoryId?: string[];
    /**
     * 教师账号（传参用）@Transient
     */
    teacherIds?: string[];
    /**
     * 授权方案名称
     */
    title?: string;
  };
  "BaseResponseBody«UserQRLoginRecord»": {
    /**
     * 响应实体
     */
    data?: definitions["UserQRLoginRecord"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«PageResponse«CountStudyNoteWithCase»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«CountStudyNoteWithCase»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«List«TeacherCaseChapter»»": {
    /**
     * 响应实体
     */
    data?: definitions["TeacherCaseChapter"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  TeacherCases: {
    /**
     * 附件列表@Transient
     */
    appendixList: definitions["TeacherCaseAppendix"][];
    /**
     * 案例封面(图片路径)
     */
    caseCover: string;
    /**
     * 章节列表@Transient
     */
    chapterList: definitions["TeacherCaseChapter"][];
    /**
     * 当前案例总课时数@Transient
     */
    countCasePeriod: number;
    /**
     * 当前案例已学习课时数@Transient
     */
    countfinishedPeriod: number;
    /**
     * 案例目标
     */
    goal: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 案例简介
     */
    intro: string;
    /**
     * 所属二级分类(二级分类Id)
     */
    juniorCategory: string;
    /**
     * 二级分类名@Transient
     */
    juniorCategoryName: string;
    /**
     * 最近学习课时Id@Transient
     */
    lastStudyPeriodId: string;
    /**
     * 案例名称(案例标题)
     */
    mainTitle: string;
    /**
     * 是否是推荐案例:是/否
     */
    recommended: boolean;
    /**
     * 所属一级分类(一级分类Id)
     */
    seniorCategory: string;
    /**
     * 一级分类名@Transient
     */
    seniorCategoryName: string;
    /**
     * 原二级分类Id
     */
    sourceJuniorCategoryId: string;
    /**
     * 案例状态(int):0－已关闭/1-未发布/2－已发布
     */
    status: number;
    /**
     * 学习进度@Transient
     */
    studyProgress: number;
    /**
     * 学习状态@Transient
     */
    studyStatus: string;
    /**
     * 案例副标题
     */
    subTitle: string;
    /**
     * 适应人群
     */
    suitableCrowd: string;
    /**
     * 标签列表@Transient
     */
    tagList: definitions["CaseTag"][];
    /**
     * 案例教师名@Transient
     */
    teacherName: string;
    /**
     * 是否是典型案例:是/否
     */
    typical: boolean;
    /**
     * 更新时间
     */
    updateDate: string;
    /**
     * 创建人(用户id)
     */
    userId: string;
  };
  "BaseResponseBody«TeacherCases»": {
    /**
     * 响应实体
     */
    data?: definitions["TeacherCases"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  GetByIdRequest: {
    /**
     * id
     */
    id: string;
  };
  InsertStudentRes: {
    /**
     * 错误信息
     */
    errorMessage?: string[];
    /**
     * 成功条数
     */
    successNum?: number;
  };
  "BaseResponseBody«PageResponse«TeacherCases»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«TeacherCases»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«CaseChapterExam»": {
    /**
     * 响应实体
     */
    data?: definitions["CaseChapterExam"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  ExportClassMemberRequest: {
    /**
     * 班级Id
     */
    classId?: string;
    /**
     * 用户Id
     */
    userIds?: string[];
  };
  "PageResponse«CaseAppendix»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["CaseAppendix"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  "公共REST返回Body对象«ClassMember»": {
    /**
     * 响应实体
     */
    data?: definitions["ClassMember"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "PageResponse«CaseNote»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["CaseNote"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  "BaseResponseBody«List«CaseCategory»»": {
    /**
     * 响应实体
     */
    data?: definitions["CaseCategory"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "公共REST返回Body对象«UserInfo»": {
    /**
     * 响应实体
     */
    data?: definitions["UserInfo"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  CountCasesAndPeriods: {
    /**
     * 系统案例数
     */
    casesCount?: number;
    /**
     * 系统章节数
     */
    periodsCount?: number;
  };
  KeywordRequest: {
    /**
     * 关键字
     */
    keyword?: string;
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
  };
  "公共REST返回Body对象«PageResponse«CaseNote»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«CaseNote»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«User»": {
    /**
     * 响应实体
     */
    data?: definitions["User"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  CaseChapterPeriod: {
    /**
     * 案例Id
     */
    caseId?: string;
    /**
     * 章节Id
     */
    chapterId?: string;
    /**
     * 创建日期
     */
    createPeriodDate?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 放入视频/音频的方式:0-上传/1-从案例文件中选择/2-网络URL
     */
    inputMark?: number;
    /**
     * 课时内容/上传音频/视频的服务器资源/案例附件Id/网络视频链接
     */
    periodContent?: string;
    /**
     * 课时摘要
     */
    periodDigest?: string;
    /**
     * 课时排序
     */
    periodSeq?: number;
    /**
     * 当前课时的学习状态:0-未学习/1-学习中,2-完成@Transient
     */
    periodStatus?: number;
    /**
     * 课时标题
     */
    periodTitle?: string;
    /**
     * 课时类型(int):图文/视频/音频
     */
    periodType?: number;
    /**
     * 创建人
     */
    userId?: string;
  };
  "BaseResponseBody«string»": {
    /**
     * 响应实体
     */
    data?: string;
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  CaseChapter: {
    /**
     * 案例Id
     */
    caseId?: string;
    /**
     * 章节排序
     */
    chapterSeq?: number;
    /**
     * 标题(章节名称)
     */
    chapterTitle?: string;
    /**
     * 创建日期
     */
    createChapterDate?: string;
    /**
     * 测验列表@Transient
     */
    examList?: definitions["CaseChapterExam"][];
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 课时列表@Transient
     */
    periodList?: definitions["CaseChapterPeriod"][];
    /**
     * 创建人
     */
    userId?: string;
  };
  "PageResponse«TeacherCaseIndex»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["TeacherCaseIndex"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  "BaseResponseBody«List«User»»": {
    /**
     * 响应实体
     */
    data?: definitions["User"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  AppendixPageByCaseMark: {
    /**
     * 文件标识:0-资料文件/1-备用文件
     */
    appendixMark: number;
    /**
     * 案例Id
     */
    caseId: string;
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
  };
  ClassMemberPk: {
    /**
     * 班级Id
     */
    classId?: string;
    /**
     * 学员Id
     */
    userId?: string;
  };
  "BaseResponseBody«ScoreDetail»": {
    /**
     * 响应实体
     */
    data?: definitions["ScoreDetail"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  ClassMember: {
    /**
     * 班级Id@Transient
     */
    classId?: string;
    classMemberPk?: definitions["ClassMemberPk"];
    /**
     * 班级名称 @Transient
     */
    className?: string;
    /**
     * 是否禁用 @Transient
     */
    disable?: boolean;
    /**
     * 学生头像 @Transient
     */
    headPath?: string;
    /**
     * 学生名称 @Transient
     */
    name?: string;
    /**
     * 教师账号 @Transient
     */
    teacherCodes?: string;
    /**
     * 教师名称 @Transient
     */
    teacherNames?: string;
    /**
     * 学员Id@Transient
     */
    userId?: string;
  };
  "公共REST返回Body对象«PageResponse«Class»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«Class»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  CaseCategory: {
    /**
     * 是否能删除 ture-能删,false-不能删
     */
    canDel?: boolean;
    /**
     * 案例数量@Transient
     */
    caseCount?: number;
    /**
     * 分类编码
     */
    categoryCode?: string;
    /**
     * 分类描述
     */
    categoryDescribe?: string;
    /**
     * 分类名称
     */
    categoryName?: string;
    /**
     * 二级分类@Transient
     */
    childList?: definitions["CaseCategory"][];
    /**
     * 是否显示 true-显示,false-不显示
     */
    display?: boolean;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 父级分类Id 如果为父级 NULL
     */
    parentId?: string;
    /**
     * 排序
     */
    seq?: number;
    /**
     * 教师二级分类@Transient
     */
    teacherChildList?: definitions["TeacherCaseCategory"][];
    /**
     * 修改时间
     */
    updateDate?: string;
    /**
     * 创建人
     */
    userId?: string;
  };
  ExamineExistUser: {
    /**
     * 该用户是否存在授权方案
     */
    existData?: boolean;
    /**
     * 教师账号
     */
    userId?: string;
    /**
     * 教师名
     */
    userName?: string;
  };
  CasesPageByCategory: {
    /**
     * 附件列表@Transient
     */
    appendixList?: definitions["CaseAppendix"][];
    /**
     * 案例封面(图片路径)
     */
    caseCover?: string;
    /**
     * 章节列表@Transient
     */
    chapterList?: definitions["CaseChapter"][];
    /**
     * 创建人用户名
     */
    creatorName?: string;
    /**
     * 案例目标
     */
    goal?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 案例简介
     */
    intro?: string;
    /**
     * 所属二级分类(二级分类Id)
     */
    juniorCategory?: string;
    /**
     * 二级分类名
     */
    juniorCategoryName?: string;
    /**
     * 案例名称(案例标题)
     */
    mainTitle?: string;
    /**
     * 是否是推荐案例:true-是/false-否
     */
    recommended?: boolean;
    /**
     * 所属一级分类(一级分类Id)
     */
    seniorCategory?: string;
    /**
     * 一级分类名
     */
    seniorCategoryName?: string;
    /**
     * 案例状态(int):0－已关闭/1-未发布/2－已发布
     */
    status?: number;
    /**
     * 学习记录数
     */
    studyRecordCount?: number;
    /**
     * 案例副标题
     */
    subTitle?: string;
    /**
     * 适应人群
     */
    suitableCrowd?: string;
    /**
     * 标签列表@Transient
     */
    tagList?: definitions["CaseTag"][];
    /**
     * 是否是典型案例:true-是/false-否
     */
    typical?: boolean;
    /**
     * 更新时间
     */
    updateDate?: string;
    /**
     * 创建人(用户id)
     */
    userId?: string;
  };
  "PageResponse«ExamineRelation»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["ExamineRelation"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  "Page«UserLoginHistory»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["UserLoginHistory"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  "BaseResponseBody«CaseChapter»": {
    /**
     * 响应实体
     */
    data?: definitions["CaseChapter"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "公共REST返回Body对象«List«CaseCategory»»": {
    /**
     * 响应实体
     */
    data?: definitions["CaseCategory"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  EditCaseRequest: {
    /**
     * 附件列表@Transient
     */
    appendixList?: definitions["CaseAppendix"][];
    /**
     * 案例封面(图片路径)
     */
    caseCover?: string;
    /**
     * 章节列表@Transient
     */
    chapterList?: definitions["CaseChapter"][];
    /**
     * 案例目标
     */
    goal?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 案例简介
     */
    intro?: string;
    /**
     * 所属二级分类(二级分类Id)
     */
    juniorCategory?: string;
    /**
     * 案例名称(案例标题)
     */
    mainTitle?: string;
    /**
     * 是否是推荐案例:true-是/false-否
     */
    recommended?: boolean;
    /**
     * 所属一级分类(一级分类Id)
     */
    seniorCategory?: string;
    /**
     * 案例状态(int):0－已关闭/1-未发布/2－已发布
     */
    status?: number;
    /**
     * 案例副标题
     */
    subTitle?: string;
    /**
     * 适应人群
     */
    suitableCrowd?: string;
    /**
     * 标签列表@Transient
     */
    tagList?: definitions["CaseTag"][];
    /**
     * 标签名对象
     */
    tagNameList?: string[];
    /**
     * 是否是典型案例:true-是/false-否
     */
    typical?: boolean;
    /**
     * 更新时间
     */
    updateDate?: string;
    /**
     * 创建人(用户id)
     */
    userId?: string;
  };
  "PageResponse«TeacherCaseAppendix»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["TeacherCaseAppendix"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  CaseToTag: {
    /**
     * 案例Id
     */
    caseId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 标签Id
     */
    tagId?: string;
  };
  "PageResponse«TeacherCaseStuProgress»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["TeacherCaseStuProgress"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  "Page«CasesPageByCategory»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["CasesPageByCategory"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  "BaseResponseBody«CountCasesAndPeriods»": {
    /**
     * 响应实体
     */
    data?: definitions["CountCasesAndPeriods"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«List«StudyStatistResponse»»": {
    /**
     * 响应实体
     */
    data?: definitions["StudyStatistResponse"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "公共REST返回Body对象«PageResponse«ExamineRelation»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«ExamineRelation»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«InsertStudentRes»": {
    /**
     * 响应实体
     */
    data?: definitions["InsertStudentRes"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  NlpWordSimEmbeddingRequest: {
    /**
     * 词1
     */
    word_1: string;
    /**
     * 词1
     */
    word_2: string;
  };
  "PageResponse«ClassMemberInfo»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["ClassMemberInfo"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  "BaseResponseBody«Cases»": {
    /**
     * 响应实体
     */
    data?: definitions["Cases"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "PageResponse«ExamineExistUser»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["ExamineExistUser"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  CountStudyNoteWithCase: {
    /**
     * 案例封面
     */
    caseCover?: string;
    /**
     * 案例Id
     */
    caseId?: string;
    /**
     * 案例名
     */
    caseName?: string;
    /**
     * 拥有笔记数
     */
    countNote?: number;
    /**
     * 最后更新时间
     */
    lastUpdate?: string;
  };
  公共REST返回Body对象: {
    /**
     * 响应实体
     */
    data?: { [key: string]: any };
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "公共REST返回Body对象«Page«Class»»": {
    /**
     * 响应实体
     */
    data?: definitions["Page«Class»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "PageResponse«TeacherInfoMemberResp»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["TeacherInfoMemberResp"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  StudyRecordPage: {
    /**
     * 异常标记@Transient
     */
    abnormalMark?: boolean;
    /**
     * 案例Id
     */
    caseId?: string;
    /**
     * 完成时间
     */
    doneDate?: string;
    /**
     * 学习时长(秒数)
     */
    duration?: number;
    /**
     * 学习设备
     */
    equipment?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 一级分类Id
     */
    seniorCategoryId?: string;
    /**
     * 加入时间
     */
    startDate?: string;
    /**
     * 首次访问课时页时间
     */
    startPeriodDate?: string;
    /**
     * 学习进度(百分数)
     */
    studyProgress?: number;
    /**
     * 学习状态:0-待学习/1-学习中/2-已完成/-1-授权状态
     */
    studyStatus?: number;
    /**
     * 案例名称
     */
    teacherCaseName?: string;
    /**
     * 用户头像
     */
    userCover?: string;
    /**
     * 用户id
     */
    userId?: string;
    /**
     * 用户名称
     */
    username?: string;
  };
  TeacherCaseIndex: {
    /**
     * 案例封面
     */
    caseCover: string;
    /**
     * 案例Id
     */
    caseId: string;
    /**
     * 案例名称
     */
    caseName: string;
    /**
     * 推荐指数
     */
    recommendIndex: number;
    /**
     * 学员数
     */
    stuCount: number;
    /**
     * 用户头像
     */
    userCover: string;
    /**
     * 用户名
     */
    userName: string;
  };
  StudyRecordStatist: {
    tableData?: { [key: string]: any }[];
    tableName?: { [key: string]: any }[];
  };
  AddUserRequest: {
    /**
     * 账号
     */
    code?: string;
    /**
     * 邮箱
     */
    email?: string;
    /**
     * 是否也是教师
     */
    isTeacher?: string;
    /**
     * 注册姓名
     */
    name?: string;
  };
  ChangeUserSignatureRequest: {
    /**
     * 账号
     */
    code?: string;
    /**
     * 用户名称
     */
    name?: string;
    /**
     * 个人签名
     */
    personalSignature?: string;
  };
  "BaseResponseBody«CountRecordsByType»": {
    /**
     * 响应实体
     */
    data?: definitions["CountRecordsByType"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  NlpLexerRequest: {
    /**
     * 待分析文本（目前仅支持GBK编码），长度不超过65536字节
     */
    text: string;
  };
  ListClassInfoMemberRequest: {
    /**
     * 班级Id
     */
    classId?: string;
    /**
     * 班级名模糊查询
     */
    classNameLike?: string;
    /**
     * 创建日期 格式：2020-11-04
     */
    createTime?: string;
    /**
     * 是否禁用
     */
    disable?: boolean;
    /**
     * 用户名模糊查询（（名字、手机、邮箱））
     */
    keyWord?: string;
    /**
     * 排序列名(userName,phone,sex,school,lastLoginTime)
     */
    orderColumnName?: string;
    /**
     * 是否降序
     */
    orderDesc?: boolean;
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
    /**
     * 教师Id
     */
    teacherId?: string;
    /**
     * 用户Id
     */
    userId?: string;
  };
  "BaseResponseBody«BPhotoInfo»": {
    /**
     * 响应实体
     */
    data?: definitions["BPhotoInfo"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«Array«int»»": {
    /**
     * 响应实体
     */
    data?: number[];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«Page«CasesPageByCategory»»": {
    /**
     * 响应实体
     */
    data?: definitions["Page«CasesPageByCategory»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  StudyRecordInfo: {
    /**
     * 案例Id
     */
    caseId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 课时Id
     */
    periodId?: string;
    /**
     * 学习课时进度 1-学习中,2-完成
     */
    progress?: number;
    /**
     * 记录Id
     */
    recordId?: string;
    /**
     * 学习时间
     */
    studyDate?: string;
    /**
     * 用户Id
     */
    userId?: string;
  };
  "BaseResponseBody«Page«User»»": {
    /**
     * 响应实体
     */
    data?: definitions["Page«User»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  VersionResult: {
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success?: boolean;
    /**
     * 版本号
     */
    version?: string;
  };
  "BaseResponseBody«object»": {
    /**
     * 响应实体
     */
    data?: { [key: string]: any };
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "公共REST返回Body对象«Examine»": {
    /**
     * 响应实体
     */
    data?: definitions["Examine"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  GetScoreDetailRequest: {
    /**
     * 学生Id
     */
    stuId?: string;
  };
  "BaseResponseBody«TeacherCaseChapter»": {
    /**
     * 响应实体
     */
    data?: definitions["TeacherCaseChapter"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  BaseUserCodeRequest: {
    /**
     * 账号
     */
    code?: string;
  };
  User: {
    /**
     * 角色.是否是管理员
     */
    admin?: boolean;
    /**
     * 年龄
     */
    age?: number;
    /**
     * 班级名称
     */
    className?: string;
    /**
     * 代码
     */
    code?: string;
    /**
     * 创建(注册)时间
     */
    createTime?: string;
    /**
     * 是否禁用
     */
    disable?: boolean;
    /**
     * 邮箱
     */
    email?: string;
    /**
     * 个人头像相对地址
     */
    headImagePath?: string;
    /**
     * 个人主页
     */
    homePage?: string;
    /**
     * 最近登录地址
     */
    lastestLoginAddr?: string;
    /**
     * 最近登录IP
     */
    lastestLoginIp?: string;
    /**
     * 最近登录时间
     */
    lastestLoginTime?: string;
    /**
     * 名称
     */
    name?: string;
    /**
     * 昵称
     */
    nickname?: string;
    /**
     * 生日
     */
    personalSignature?: string;
    /**
     * 个人简介
     */
    resume?: string;
    /**
     * 教育水平
     */
    selfIntroduction?: string;
    /**
     * 性别:0:女;1:男
     */
    sex?: number;
    /**
     * 角色.是否是学生
     */
    student?: boolean;
    /**
     * 角色.是否是教师
     */
    teacher?: boolean;
    /**
     * 职业
     */
    title?: string;
  };
  IdListRequest: {
    /**
     * 用于做批量功能接口的输入Id集合
     */
    idList?: string[];
  };
  NoteInfoInMyStudy: {
    /**
     * 案例Id
     */
    caseId?: string;
    /**
     * 笔记内容
     */
    content?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 案例标题@Transient
     */
    mainTitle?: string;
    /**
     * 课时Id
     */
    periodId?: string;
    /**
     * 课时名称
     */
    periodName?: string;
    /**
     * 课时名称@Transient
     */
    periodTitle?: string;
    /**
     * 一级分类Id
     */
    seniorCategoryId?: string;
    /**
     * 更新时间
     */
    updateDate?: string;
    /**
     * 作者(用户id)
     */
    userId?: string;
    /**
     * 作者名(用户名)@Transient
     */
    userName?: string;
  };
  "BaseResponseBody«CaseToTag»": {
    /**
     * 响应实体
     */
    data?: definitions["CaseToTag"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  IdArray: {
    /**
     * 主键集合
     */
    ids?: string[];
  };
  LoginRequest: {
    cas?: boolean;
    /**
     * 用户号
     */
    code: string;
    /**
     * 密码
     */
    password: string;
  };
  "BaseResponseBody«List«StuScore»»": {
    /**
     * 响应实体
     */
    data?: definitions["StuScore"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  ExamineRelation: {
    /**
     * 创建日期
     */
    createTime?: string;
    /**
     * 授权管理Id
     */
    examineId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 教师Id
     */
    userId?: string;
    /**
     * 教师名称
     */
    userName?: string;
  };
  "公共REST返回Body对象«Void»": {
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  StudyTopResponse: {
    /**
     * 显示文字/姓名
     */
    context?: string;
    /**
     * 总数/排名
     */
    count?: number;
    /**
     * 同比率/成绩
     */
    rate?: number;
  };
  "Page«User»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["User"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  "Page«Class»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["Class"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  "BaseResponseBody«NlpWordSimEmbeddingResponse»": {
    /**
     * 响应实体
     */
    data?: definitions["NlpWordSimEmbeddingResponse"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«List«string»»": {
    /**
     * 响应实体
     */
    data?: string[];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«List«TeacherCaseAppendix»»": {
    /**
     * 响应实体
     */
    data?: definitions["TeacherCaseAppendix"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  AllStudyRecordPageRequest: {
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
  };
  "BaseResponseBody«PageResponse«TeacherCaseIndex»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«TeacherCaseIndex»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "公共REST返回Body对象«ScoreTarget»": {
    /**
     * 响应实体
     */
    data?: definitions["ScoreTarget"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«List«RecordDistributionResponse»»": {
    /**
     * 响应实体
     */
    data?: definitions["RecordDistributionResponse"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  ClassMemberInfo: {
    /**
     * 班级Id@Transient
     */
    classId?: string;
    classMemberPk?: definitions["ClassMemberPk"];
    /**
     * 班级名称 @Transient
     */
    className?: string;
    /**
     * 是否禁用 @Transient
     */
    disable?: boolean;
    /**
     * 学生头像 @Transient
     */
    headPath?: string;
    /**
     * 最后登录时间
     */
    lastLoginTime?: string;
    /**
     * 学生名称 @Transient
     */
    name?: string;
    /**
     * 手机号
     */
    phone?: string;
    /**
     * 学校
     */
    school?: string;
    /**
     * 1男 2女 3其他
     */
    sex?: number;
    /**
     * 教师账号 @Transient
     */
    teacherCodes?: string;
    /**
     * 教师名称 @Transient
     */
    teacherNames?: string;
    /**
     * 学员Id@Transient
     */
    userId?: string;
  };
  "BaseResponseBody«Page«UserLoginHistory»»": {
    /**
     * 响应实体
     */
    data?: definitions["Page«UserLoginHistory»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  CasesWithCategoryName: {
    /**
     * 案例对象
     */
    cases?: definitions["Cases"];
    /**
     * 二级分类名
     */
    juniorCategoryName?: string;
    /**
     * 一级分类名
     */
    seniorCategoryName?: string;
    /**
     * 教师端案例对象
     */
    teacherCases?: definitions["TeacherCases"];
  };
  TeacherCaseMixResponse: {
    /**
     * 分类总数
     */
    categoryCount?: number;
    /**
     * 分类Id
     */
    categoryId?: string;
    /**
     * 分类名
     */
    categoryName?: string;
    /**
     * 占比数
     */
    mix?: number;
  };
  "公共REST返回Body对象«boolean»": {
    /**
     * 响应实体
     */
    data?: boolean;
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«TeacherCaseAppendix»": {
    /**
     * 响应实体
     */
    data?: definitions["TeacherCaseAppendix"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«CaseChapterPeriod»": {
    /**
     * 响应实体
     */
    data?: definitions["CaseChapterPeriod"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  ClassExamineCategory: {
    /**
     * 班级Id
     */
    classId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 二级分类Id（传参用）@Transient
     */
    subCategoryId?: string;
    /**
     * 创建人
     */
    userId?: string;
  };
  NlpSimnetRequest: {
    /**
     * 待比较文本1
     */
    text1: string;
    /**
     * 待比较文本2
     */
    text2: string;
  };
  TeacherCaseStuProgress: {
    /**
     * 学生code
     */
    stuCode: string;
    /**
     * 学生头像
     */
    stuHeadCover: string;
    /**
     * 学生名
     */
    stuName: string;
    /**
     * 学生该案例学习进度(百分数)
     */
    stuProgress: number;
  };
  TeacherCaseChapterPeriod: {
    /**
     * 案例Id
     */
    caseId?: string;
    /**
     * 章节Id
     */
    chapterId?: string;
    /**
     * 创建日期
     */
    createPeriodDate?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 放入视频/音频的方式:0-上传/1-从案例文件中选择/2-网络URL
     */
    inputMark?: number;
    /**
     * 课时内容/上传音频/视频的服务器资源/案例附件Id/网络视频链接
     */
    periodContent?: string;
    /**
     * 课时摘要
     */
    periodDigest?: string;
    /**
     * 课时排序
     */
    periodSeq?: number;
    /**
     * 当前课时的学习状态:0-未学习/1-学习中,2-完成@Transient
     */
    periodStatus?: number;
    /**
     * 课时标题
     */
    periodTitle?: string;
    /**
     * 课时类型(int):图文/视频/音频
     */
    periodType?: number;
    /**
     * 创建人
     */
    userId?: string;
  };
  "BaseResponseBody«PageResponse«TeacherCaseAppendix»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«TeacherCaseAppendix»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
}
